[build]
  base    = "tijolo"
  publish = "public"

[functions]
  directory = "../netlify/functions"

[[redirects]]
  from   = "/api/waitlist"
  to     = "/.netlify/functions/waitlist"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
  