[build]
  base    = "tijolo"
  publish = "public"

[[redirects]]
  from   = "/api/waitlist"
  to     = "/.netlify/functions/waitlist"
  status = 200

[functions]
  directory = "../netlify/functions"
  